accordion-padding = 30
after-login-command = []
after-startup-command = []
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
exec-on-workspace-change = []
on-focus-changed = []
on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]
start-at-login = false

[gaps.inner]
horizontal = 10
vertical = 10

[gaps.outer]
bottom = 10
left = 10
right = 10
top = 10

[key-mapping]
preset = "qwerty"

[mode.main.binding]
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-5 = "workspace 5"
alt-6 = "workspace 6"
alt-comma = "layout accordion horizontal vertical"
alt-e = "focus up"
alt-h = "focus left"
alt-i = "focus right"
alt-n = "focus down"
alt-shift-0 = "balance-sizes"
alt-shift-1 = "move-node-to-workspace 1"
alt-shift-2 = "move-node-to-workspace 2"
alt-shift-3 = "move-node-to-workspace 3"
alt-shift-4 = "move-node-to-workspace 4"
alt-shift-5 = "move-node-to-workspace 5"
alt-shift-6 = "move-node-to-workspace 6"
alt-shift-e = "move up"
alt-shift-equal = "resize smart +50"
alt-shift-h = "move left"
alt-shift-i = "move right"
alt-shift-minus = "resize smart -50"
alt-shift-n = "move down"
alt-slash = "layout tiles horizontal vertical"

[[on-window-detected]]
if.app-id = "com.libretro.dist.RetroArch"
run = ["layout floating"]

[[on-window-detected]]
if.app-id = "com.googlecode.iterm2"
run = ["layout floating"]

[workspace-to-monitor-force-assignment]
